services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory_backend
    ports:
      - "${APP_PORT:-85}:85"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: inventory_frontend
    ports:
      - "${PORT:-8089}:80"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true
