version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: inventory_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory_backend
    ports:
      - "85:85"
    environment:
      - DB_HOST=${DB_HOST}
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
      - dashboard_dashboard-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory_frontend
    ports:
      - "8089:80"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  dashboard_dashboard-network:
    external: true

volumes:
  redis_data:
